### ISSUE TITLE
Stop autogenerating the `body` field

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina-graphql-gateway#214]
## Summary
 
I would love a way to hide the body from the sidebar when a form is registered.

### Basic example

My markdown content only uses frontmatter, so it makes the editing experience a bit more confusing for editors:
<img width="424" alt="Screen Shot 2021-05-21 at 9 33 38 AM" src="https://user-images.githubusercontent.com/3323181/119137928-b5150580-ba17-11eb-976f-2a7264d663af.png">

### Motivation

Now that we can (soon) use json files, this is not as critical, however I think we'll still run into users using frontmatter without a markdown body. This will also be typical for any block-based pages

**Comment by jeffsee55** [comment]
I think what's easiest here is to just stop adding a `body` field by default. It's kind of confusing that you get that field "for free" without specifying it in your `defineSchema` anyway. 

The caveat here is that `body` would have to be a sort of reserved field _name_. Meaning that if you're defining your schema you'd have to know that if you call something `body` and your collection is formatted for `markdown`, that bit of data will end up in the body. And if you're using `json` it'll just be another field. And to add to that, if you use `body` - it _must_ be a text or textarea (or rich text) field. Since that's all we can represent in the body of a markdown file.

Does that make sense?

```ts
defineSchema({
  collections: [
    {
      label: "Blog Posts",
      name: "posts",
      path: "content/posts",
      templates: [
        {
          label: "Article",
          name: "article",
          fields: [
            {
              type: "text",
              label: "Title",
              name: "title",
            },
            {
              type: "reference",
              label: "Author",
              name: "author",
              collection: "authors",
            },
            {
              label: "Body",
              name: "body", // when this is called "body"
              type: "text", // this _must_ be either `text` or `textarea`
            }
          ],
        },
      ],
    },
  ]
})
```

**Comment by jeffsee55** [comment]
We'll continue to serve `_body` in the `data` payload but stop auto-building `_body` as a `form`. Consider the best way to add warnings to make the user aware of this change.

API versioning would be a nice thing to have for this
