### ISSUE TITLE
Better error message when `schema.ts` is not on Github

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tina-graphql-gateway#216]
## Description

When querying content from Github on Tina Cloud. I used the `main` branch that did not have any content as I was working from `tina-cloud` branch. I got no error in the client it was just in a loading state forever. When looking in the network tab my request failed and I got this message back.

`{"message": "something went wrong"}`

### Expected result

It should give a more useful error message when the content or `schema.ts` is not on Github.

**Comment by Enigmatical** [comment]
There's two tasks to be addressed here:
* Determine if the GraphQL CLI/Package/Client is swallowing or surfacing 400/500 Errors and responding with 200s.  If we are, we should stop doing that.
* Use better error messages instead of "Something went wrong" - could show whatever Tina Cloud is responding with?
