### ISSUE TITLE
Bring Cloudinary support into starter

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tina-graphql-gateway#233]
We'll be revitalizing the Cloudinary POC and improving it to the point where we can support a full media story for Tina Cloud. 

Related tickets:
https://github.com/tinacms/tinacms/issues/1843
https://github.com/tinacms/tinacms/issues/1842
https://github.com/tinacms/tina-graphql-gateway/issues/234

**Comment by logan-anderson** [comment]
I am not super familiar with how the Image component works but I am running into some weird Issues on the starter. I am using the cloudinary media store on the starter. [Code can be found here](https://github.com/tinacms/tina-cloud-starter/tree/media-demo).

To start I added the necessary API endpoints and ENV vars. Everything in media manager seems to be working.

### What works
- img listing
- img uploading
- img deleting

When it comes to integrating the image component itself I am getting some weird behaviour. 

The setup for adding the component looks like this
```ts
const [payload, isLoading] = useGraphqlForms({
    query: (gql) => gql(props.query),
    variables: props.variables || {},
    formify: ({ createForm, formConfig, skip }) => {
      formConfig.fields.forEach((field) => {
        if (field.name === "heroImg") {
          field.component = "image";
        }
      });
      return createForm(formConfig);
    },
  });
```

But when I do that the data looks like this

```json
{
  "__typename": "Article_Doc_Data",
  "heroImg": {
    "id": "sample",
    "filename": "sample",
    "directory": ".",
    "previewSrc": "https://res.cloudinary.com/forestry-logan/image/upload/c_fill,g_auto,h_56,w_56/sample",
    "type": "file"
  },
//...
}
```
And I would expect it to look like this
{
  "__typename": "Article_Doc_Data",
  "heroImg":https://res.cloudinary.com/forestry-logan/image/upload/c_fill,g_auto,h_56,w_56/sampl
  },
//...
}

Along with this I am unable to save (probably because of the data shape) and the image preview does not work.

![Screen Shot 2021-06-03 at 9 25 31 AM](https://user-images.githubusercontent.com/43075109/120644411-ad108900-c44d-11eb-94e7-257510608a76.png)

consulting the docs, I thought I must be missing some config for the image field so I tried adding

```js
  if (field.name === "heroImg") {
          field.component = "image";
          field.previewSrc = (img) => img.previewSrc;
}        
```

When doing this the image preview was working but the shape of the data stayed the same and I was still unable to save.

![Screen Shot 2021-06-03 at 9 28 46 AM](https://user-images.githubusercontent.com/43075109/120645027-5d7e8d00-c44e-11eb-8ca1-3198aa59ccf5.png)

Lastly, I tried adding the parse function to change the shape of the data.

```js
 if (field.name === "heroImg") {
          field.component = "image";
          field.previewSrc = (img) => img.previewSrc;
          field.parse = (img: Media) => {
            return img.previewSrc;
          };
}
```
When all this was added the preview did not work.
![Screen Shot 2021-06-03 at 9 33 29 AM](https://user-images.githubusercontent.com/43075109/120645458-d382f400-c44e-11eb-905e-43c9f6b430b7.png)
and the data was null
```json
{
  "__typename": "Article_Doc_Data",
  "heroImg": null,
  "title": "Vote For Pedro",
}
```
Not sure what to try next? would love to hear your thoughts @jeffsee55 and @dwalkr

**Comment by DirtyF** [comment]
Does Cloudinary support means using the default media manager? Could this be another plugin that loads the Cloudinary widget and let you upload files?

**Comment by jeffsee55** [comment]
@DirtyF it means using our media manager with a media store written that integrates with Cloudinary. We're close enough to having this work that it'd be more trouble to go with a UI widget provided by Cloudinary at this point.

**Comment by jeffsee55** [comment]
Pulling @logan-anderson's current work into this monorepo and leaving the current repo more or less untouched so the "open authoring" demo can continue to work.

**Comment by jeffsee55** [comment]
The next/cloudinary package should live in the TinaCMS monorepo

**Comment by jeffsee55** [comment]
@dwalkr one thing that's come from this is that we're implicitly relying on whoever builds a media store to work with `useGraphQLForms` will need to support the `parse` function - which isn't explicitly required by the current media interface. Do you see potential issues with this being enforced as a mandatory property on that?

**Comment by dwalkr** [comment]
I have a feeling that the `Media` and `MediaStore` interfaces need some clarity + cleaning up. My main concern with adding a mandatory `parse` method to the `MediaStore` interface is that it's just another thing that overlaps other elements of these interfaces. I'm worried that carrying a mandatory `parse` into the `MediaStore` is just going to further confuse what is already a bit of muddiness regarding how we get the values we really want (production URL and preview URL) from these interfaces.

in the short term, making `parse` optional and including a default behavior might be better until we can straighten these things out. My gut reaction is that Tina Cloud should be saving the `Media` object's `id` field. But unless we clearly define how a Media Store should convert a scalar `id` into the correct URL when building for production, we're mixing concerns a little bit. (in practice, a filename or URL is a good unique identifier, but I can see how that might be a bit misleading.)

**Comment by dwalkr** [comment]
This is a random place to note this, but I also want to point out that the Media Library could potentially include non-image media as well. In this case, `previewSrc` still applies - the media library should be able to represent the media as a static image one way or another (we're getting around this with the `Media#type` field.) In that case though, obviously you wouldn't want to save `previewSrc` as the identifier for that piece of content.

**Comment by jeffsee55** [comment]
> I have a feeling that the Media and MediaStore interfaces need some clarity + cleaning up

@dwalkr I'd definitely find it worthwhile to step through that together and get a feel for where it's responsibilities start/stop.

And I hear you about the idea that storing the "id" is likely a more correct solution in some cases. I can think of scenarios where I'd want the id and some when I'd want the src.

In general the main point I care about is this: developers shouldn't need to do _anything_ at the field-level to support images. That logic can be handled entirely from the media store implementation and only in rare occasions it may make sense to dig into the `previewSrc` and `parse` functions at the field-level.

**Comment by dwalkr** [comment]
> I can think of scenarios where I'd want the id and some when I'd want the src.

Absolutely. I'm thinking the ideal solution would be store an ID + have an easy way to derive the src from the id. In common use cases they could be the same thing, but the semantics are important for those uncommon cases.

> In general the main point I care about is this: developers shouldn't need to do anything at the field-level to support images. That logic can be handled entirely from the media store implementation and only in rare occasions it may make sense to dig into the previewSrc and parse functions at the field-level.

Agree 100%. The APIs in the image field predate the existence of media stores, so it's kind of stuck between two different worlds. If you have a media store set up, your image field shouldn't need to contain any special logic.
